[platformio]
default_envs = esp32-client

[env:esp32-server]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default.csv

lib_deps =
    tzapu/WiFiManager@^0.16.0
    bblanchon/ArduinoJson@^6.21.5
    gilmaimon/ArduinoWebsockets@^0.5.3

build_flags = 
    -D ARDUINO_LOOP_STACK_SIZE=8192

src_filter = +<*> -<client/> -<../client/>

[env:esp32-client]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    tzapu/WiFiManager@^0.16.0
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SSD1306@^2.5.7
    madhephaestus/ESP32Servo@^3.0.5
    bblanchon/ArduinoJson@^6.21.5
    gilmaimon/ArduinoWebsockets@^0.5.3

build_flags = 
    -D ARDUINO_LOOP_STACK_SIZE=8192

src_filter = +<*> -<server/> -<../server/>
